# Generated by Django 4.1.7 on 2023-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0002_login_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bus_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
