# Generated by Django 4.1.7 on 2023-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
