# Generated by Django 4.1.7 on 2023-09-14 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0005_alter_bus_arrival_time_alter_bus_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
