# Generated by Django 4.0.4 on 2023-09-22 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0006_bus_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_fare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='img',
            field=models.URLField(),
        ),
    ]
