# Generated by Django 4.0.4 on 2023-09-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0007_ticket_total_fare_alter_bus_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='total_fare',
            field=models.IntegerField(),
        ),
    ]
