# Generated by Django 4.0.4 on 2023-09-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0008_alter_ticket_total_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_fare',
        ),
    ]
