# Generated by Django 4.1.7 on 2023-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0009_remove_ticket_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_fare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
